---
services:
  api:
    image: scottishwidow/api:latest
    restart: always
    build:
      context: express
      dockerfile: Dockerfile
    ports:
      - 7070:3000
    environment:
      - ENV_VALUE
      - ENV_TOKEN
