---
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    secrets:
      - pg-password
    environment:
      - POSTGRES_USER=node
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: node-api:latest
    restart: always
    build:
      context: express
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - ENV_VALUE
      - ENV_TOKEN
      - DB_HOST=postgres
      - DB_USER=node
      - DB_DATABASE=postgres
    volumes:
      - api-data:/data
    secrets:
      - pg-password

volumes:
  api-data:
  postgres-data:

secrets:
  pg-password:
    file: ./secrets/pg-password
