---
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=node
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret12345
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: node-api:latest
    restart: always
    build:
      context: express
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - ENV_VALUE
      - ENV_TOKEN
    volumes:
      - api-data:/data
volumes:
  api-data:
  postgres-data:
