---
services:
  api:
    image: scottishwidow/api:latest
    restart: always
    build:
      context: express
      dockerfile: Dockerfile
    ports:
      - 7070:3000
    secrets:
      - pg-password
    environment:
      - ENV_VALUE
      - ENV_TOKEN
    volumes:
      - ./express:/app
    depends_on:
      - postgres
 
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - pg-password
    environment:
      POSTGRES_USER: node-api
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg-password

secrets:
  pg-password:
    file: ./secrets/pg-password

volumes:
  api-data:
  postgres-data:

