---
services:
  api:
    image: scottishwidow/api:latest
    restart: always
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - 7070:3000
    secrets:
      - pg-password
    environment:
      - ENV_VALUE
      - ENV_TOKEN
      - DB_HOST
      - DB_DATABASE
      - DB_USER
    volumes:
      - api-data:/data
      # - ./src/data:/data
    depends_on:
      postgres:
        condition: service_healthy
 
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD_FILE
    secrets:
      - pg-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5

secrets:
  pg-password:
    file: ./secrets/pg-password

volumes:
  api-data:
  postgres-data:

